# Generated by Django 5.0.4 on 2024-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudoperationsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
    ]
